### ISSUE TITLE
Make a demo page

### ISSUE THREAD

**Issue by passy** [passy/backbone.datalink#1]

**Comment by sindresorhus** [comment]
lazyyyyyyyyyyyyyyyyyyyyyyyy

**Comment by passy** [comment]
Haha, you got me. :smiling_imp:

**Comment by sindresorhus** [comment]
Feel free to point out my lazyyyyyyyyyyyyyyyyyyyyyyyyness in 1.9 years when I haven't done this: https://github.com/sindresorhus/detect-indent/issues/5
